language: cpp
before_script:
  # install dependencies
  - sudo add-apt-repository ppa:wpilib/toolchain -y
  - sudo apt-get update -q
  - sudo apt-get install frc-toolchain cmake
script:
  - ./gradlew
