language: cpp
before_script:
  # install dependencies
  - sudo add-apt-repository ppa:wpilib/toolchain -y
  - sudo apt-get update -q
  - sudo apt-get install frc-toolchain cmake
  - sudo apt-get install wget
  - git clone https://github.com/Team612/FRCpp_Build_Tools.git ./FRCBT
  - cd FRCBT
  - git clone https://github.com/Ewpratten/barebonesFRC.git ../BBFRC
  - rm -rf ./src
  - mv ../BBFRC/src ./
  - rm -rf TEAM_NAME
  - touch TEAM_NAME
  - echo "5024" >> TEAM_NAME
  - touch .build/cmake_install.cmake .build/CMakeCache.txt .build/FRCUserProgram .build/Makefile
  - git clone https://github.com/CrossTheRoadElec/Phoenix-frc-lib.git ../CTRELIB
  - mv ../CTRELIB/cpp/include/ctre /usr/local/include/
  
script:
  - make
